import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '../Navbar/Navbar';
import { FC } from 'react';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: any;
}

const MainLayout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>bUENAS PERROS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={`${styles.main} ${inter.className}`}>
        { children }
      </main>
    </>
  )
};


export default MainLayout;
